### ISSUE TITLE
アイデア出し

### ISSUE THREAD

**Issue by yamamotoAIIT** [naoki360000/TeamExcellent#3]
何を作るかアイデアだしした方が良いのでは？私自身、課題6を必死こいて実装したぐらいのレベルの初心者でして、良いアイデアは浮かんでないですが。職場ではPL/SQLとCOBOLを読む程度でして。何か思いついたら追加するので、皆さんも考えてみましょう。簡単　かつ　全員で作業できるものが良いですが。。

**Comment by yamamotoAIIT** [comment]
1つ思いつきました。プログラムの初心者である自分が何か1つ作るとしたら、AIITの成績評価ロジックを作ります。点数を渡したら、成績を返してくるだけのプログラムです。それでも、1,2時間かかるとは思いますが。テストも簡単に掛けそうですね。どなたか、rubyに詳しい人がいれば、これを拡張できると思います。私は詳しくないので言いっぱなしになってしまいますが、例えば、
・csvファイルで名前と点数が入ったファイルを作っておく
・csvファイルを読み込んで、成績をつけて表示する
・csvファイルを読み込んで、最高点の人の名前と点数を求める
・csvファイルを読み込んで、最低点の人の名前と点数を求める
・csvファイルを読み込んで、平均点を求める
とかですかね。ファイルの読み込みとかひな形があって、修正するファイルが別ファイルであれば、コンフリクトも起こらなそうですよね。これなら、全員がある程度コーディングできそうし、全員が出来なくとも誰か1人が１つできるだけで、何とか提出はできますね。どなかか、「ひな形できるよ！」って方、いると助かるんですが。

**Comment by harakoji** [comment]
パブリックリポジトリなので、ディスカッションはメールでやりましょう。
